### PR TITLE
Require pairs to be passed as arrays

### PR DESCRIPTION
**Pull request by methyl**
Hey there!

I just recently looked for a decent way of doing pattern matching in JS and it seems I finally find one, this library looks really promising!

The only problem I have is that due to (pattern, action) pairs are not grouped anyhow, using prettier messes things up:
```js
function fib(n) {
    return match(
      n,
      0,
      0,
      1,
      1,
      2,
      1,
      3,
      2,
      4,
      3,
      _,
      x => fib(x - 1) + fib(x - 2)
    )
  }
```

If we wrap each pair in an array it looks way better:
```js
function fib(n) {
    return match(
      n,
      [0, 0],
      [1, 1],
      [2, 1],
      [3, 2],
      [4, 3],
      [_, x => fib(x - 1) + fib(x - 2)]
    )
  }
```

Have you considered something like this? I know the downside is that we add some unnecessary arrays, but it's probably negligible. What we get is:
- each pattern and action logically grouped together
- great prettier formatting
- it could probably help to get rid of the pairwise call: https://github.com/santinic/pampy.js/blob/master/lib/pampy.js#L197
- much easier to type in TypeScript

Let me know what you think!

### CODE REVIEW

**Comment by santinic** [comment]
I don't know, I see your point, but my Cmd+Shift+L on IntelliJ doesn't matter that formatting. Prettifier is too dogmatic to me. You could pull-request a matchPairs (or whatever) function that calls match and uses [patt, value] pairs.
And then we will have a discussion on what is the default/suggested behaviour

**Comment by santinic** [comment]
For example, take the lisp function:

```javascript
function lisp(exp) {
    return match(exp,
        Function,           (x) => x,
        [Function, REST],   (f, rest) => f.apply(null, rest.map(lisp)),
        Array,              (l) => l.map(lisp),
        _,                  (x) => x
    );
```
It would get prettified (with the pairs notation) into:

```javascript
function lisp(exp) {
  return match(
    exp,
    [Function, x => x],
    [[Function, REST], (f, rest) => f.apply(null, rest.map(lisp))],
    [Array, l => l.map(lisp)],
    [_, x => x]
  );
}
```
Maybe you can add exceptions to prettifier, but it's not clear to me that it is an improvement.
By the way, I think the matchPairs() or matchp() function would the best way to give users more options.

**Comment by methyl** [comment]
Yeah, something like matchPairs really makes sense here. Or we could make `match` generic which is also feasible, but referring to Python's explicit is better than implicit you would rather go with matchPairs I guess.

**Comment by santinic** [comment]
yes, also it's very hard to make match() behave with/without pairs. I love the explicit matchp()

**Comment by methyl** [comment]
@santinic updated as discussed

**Comment by santinic** [comment]
Thank you Lucjan.

**Pull request merged**
